In [29]:
import torch
print(torch.__version__)

2.0.1+cpu


In [30]:
scalar = torch.tensor(2)
print(type(scalar), scalar.ndim)

<class 'torch.Tensor'> 0


In [31]:
vector = torch.tensor([1,2,3,4,5])
print(type(vector), vector.ndim)

<class 'torch.Tensor'> 1


In [32]:
matrix = torch.tensor([[1,2,3,4],
                       [4,5,6,7]])
print(type(matrix), matrix.size(), matrix.ndim)

<class 'torch.Tensor'> torch.Size([2, 4]) 2


In [33]:
matrix.size(), matrix.shape

(torch.Size([2, 4]), torch.Size([2, 4]))

Both .shape and .size() are working same the difference is as `size()` is method while `shape` is an attribute

In [34]:
torch.zeros(size=(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [35]:
torch.ones(size=(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
torch.randint(low=2, high=10, size=(2,))

tensor([8, 5])

In [37]:
torch.randn((2,3))

tensor([[ 0.8196,  0.7297,  0.0202],
        [ 1.5075, -0.2143,  0.7314]])

In [38]:
matrix*10

tensor([[10, 20, 30, 40],
        [40, 50, 60, 70]])

In [39]:
matrix.add(10)

tensor([[11, 12, 13, 14],
        [14, 15, 16, 17]])

temp = torch.

In [44]:
temp = torch.tensor([1,2,3,5,6,7])
temp = temp.view(3, 1, 2)
temp.shape

torch.Size([3, 1, 2])

In [49]:
temp

tensor([[[1, 2]],

        [[3, 5]],

        [[6, 7]]])

In [51]:
sq = torch.squeeze(temp, dim=1)

In [52]:
sq2 = temp.squeeze(dim=1)
sq2

tensor([[1, 2],
        [3, 5],
        [6, 7]])

In [53]:
assert torch.all(sq == sq2)

In [54]:
x = torch.randn(10, 10)
z2, z3, z4 = x[None], x[:, None], x[:,:,None]
print(z2.shape, z3.shape, z4.shape)

torch.Size([1, 10, 10]) torch.Size([10, 1, 10]) torch.Size([10, 10, 1])


In [71]:
import numpy as np

matrix = np.random.randn(5,10)
matrix.shape

(5, 10)

In [72]:
matrix[None].shape

(1, 5, 10)

In [73]:
tensor_matrix = torch.tensor(matrix)

In [74]:
tensor_matrix.get_device()

-1

In [76]:
unitied_matrix = torch.cat((tensor_matrix, tensor_matrix),axis=1)
unitied_matrix.shape

torch.Size([5, 20])

In [77]:
x = torch.arange(1,11, 1)
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
values, armin = x.reshape(5,2).min(dim=0)
print(values, armin)

tensor([1, 2]) tensor([0, 0])


In [87]:
# concept of permutation

temp = torch.randn((10,20,30))
print(temp.shape)
print("Shape after permute: ",temp.permute(2,0,1).shape)

torch.Size([10, 20, 30])
Shape after permute:  torch.Size([30, 10, 20])


So permutation you can rotate the axis position according to your will or need.

In [100]:
x = torch.tensor(list(range(10)), dtype=torch.float32, requires_grad=True)
pw_2 = x.pow(2).sum()

In [101]:
pw_2.backward()

In [104]:
x.grad

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [106]:
x = torch.randn(1, 6400)
y = torch.randn(6400, 5000)

device = 'cuda' if torch.cuda.is_available() else "cpu"

x , y = x.to(device), y.to(device)
%timeit z = (x@y)

16 ms ± 613 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [107]:
x = np.random.randn(1,6400)
y = np.random.randn(6400, 5000)

%timeit z = np.matmul(x,y)

35.4 ms ± 2.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [111]:
x = [[1,2], [3,4], [5,6], [7,8]]
y = [[3], [7], [11], [15]]

x = torch.tensor(x).float()
y = torch.tensor(y, dtype=torch.float32)
x.dtype, y.dtype

(torch.float32, torch.float32)